//
// Created by timob on 22.02.2026.
//

#ifndef SpaceMachine_SPACEMACHINE_TEMPLATESPACEMACHINE_HPP
#define SpaceMachine_SPACEMACHINE_TEMPLATESPACEMACHINE_HPP

#endif // SpaceMachine_SPACEMACHINE_TEMPLATESPACEMACHINE_HPP
